# tasks file for gikeymarica.nerdfonts
---

- name: "Make sure font directory exists."
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  with_items:
    - /usr/share/fonts/nerdfonts
    - /opt/nerdfonts/
    - "/opt/nerdfonts/v{{ nf_version }}"

- name: "Create system folders for each font"
  ansible.builtin.file:
    path: "/usr/share/fonts/nerdfonts/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  with_items: "{{  nf_fonts }}"

- name: Download nerd fonts.
  ansible.builtin.get_url:
    url: "{{ nf_dl_base }}/v{{ nf_version }}/{{ item }}.tar.xz"
    # example
    # https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/3270.tar.xz
    dest: "/opt/nerdfonts/v{{ nf_version }}/{{ item }}.tar.xz"
    group: root
    owner: root
    mode: "0644"
    # force: false
  with_items: "{{ nf_fonts }}"

- name: "Unarchive all dowloaded fonts."
  ansible.builtin.unarchive:
    src: "/opt/nerdfonts/v{{ nf_version }}/{{ item }}.tar.xz"
    dest: "/usr/share/fonts/nerdfonts/{{ item }}"
    remote_src: true
  with_items: "{{ nf_fonts }}"
  notify: scan_fonts

...
# vim: ft=yaml.ansible :
