# tasks file for gikeymarica.nerdfonts
---
- name: Make sure the nf_user has been defined
  tags: always
  ansible.builtin.fail:
    msg: "FAILURE! 'nf_user' variable must be defined. See README"
  when: nf_user

- name: Make sure font directory exists
  ansible.builtin.file:
    path: "/home/{{ nf_user }}/.local/share/fonts"
    owner: "{{ nf_user }}"
    group: "{{ nf_user }}"
    mode: "0644"

...
# vim: ft=yaml.ansible :
